### ISSUE TITLE
[PE-D][Tester E] Typo in the GUI Summary part of the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-2/tp#161]
The description of the green border should be "user has an interview"

The description of the red border has a typo/grammatical error, (not -> no)

![image.png](https://raw.githubusercontent.com/marcellaantania/ped/main/files/9a182352-a3bf-4fac-ad84-e1967b7f093b.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: marcellaantania/ped#1

**Comment by kiwibang** [comment]
Is duplicate, solved in #190 #191
