### ISSUE TITLE
[PE-D][Tester C] Interview start and end time

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-2/tp#169]
right now it is possible to enter an interview start time that is later than the end time

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: beatricecst/ped#6

**Comment by ghost** [comment]
Not an issue, it checks for this behaviour

**Comment by jingjie88** [comment]
<img width="1710" alt="image" src="https://github.com/AY2324S1-CS2103T-T11-2/tp/assets/71217424/fb0a054b-a390-4759-82b0-d8816bfef719">
