### ISSUE TITLE
[PE-D][Tester D] Error message for add-i

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-2/tp#184]
When the timing is not specified for start/, the error message printed is about an invalid date:

![image.png](https://raw.githubusercontent.com/emzm2023/ped/main/files/6e47c14c-7df6-4db0-9c44-e9910196d2ef.png)

Might want to fix this up to be more specific so that it's clearer for the user

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: emzm2023/ped#6

**Comment by ghost** [comment]
Feature flaw, cannot be fixed, update planned enhancements section in the DG to address this

**Comment by kiwibang** [comment]
Add this to "planned enhancements" section.
