### ISSUE TITLE
[PE-D][Tester F] Missing cell information

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-2/tp#192]
![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/d0272446-957b-4bd7-921f-89c9c72fe9a7.png)

The cell is missing an entry which could cause confusion. 
It seems that the applicant and interview entries are not directly related. Thus, to avoid the issue of this missing cell. The team could consider making the tables for applicant and interview separate to avoid confusion from the user.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: shashahchk/ped#3

**Comment by ghost** [comment]
Update UG to 2 seperate tables.
