### ISSUE TITLE
[PE-D][Tester F] Add command not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T11-2/tp#194]
![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/ad5bcae8-60c4-405d-9c73-ee5d5f87c4ca.png)

This is the error encountered when typed in the following:
add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague

Expected output: successful applicant added and the applicant listed on the GUI.
Actual: error message and unable to add applicant as command is not recognised.

I believe that to help the user understand potential problems and also to faciliate debugging, the team can consider adding error message specific to the issue. E.g.invalid name, etc.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: shashahchk/ped#5

**Comment by ghost** [comment]
Duplicate bug - Will be fixed in #195 UG update - Documentation error
