### ISSUE TITLE
[PE-D][Tester F] Add Interview Command parameters different from UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-2/tp#195]
![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/017ecadc-4ef0-47f2-8899-d8bcda791f2b.png)
Expected: successful interview added
Actual: error, parameters required are different from the ones specified in DG.
Namely, "time" vs "start" and "end"
![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/791c59c1-69a3-4048-b3bb-8af20214e4b4.png)

Perhaps the team could choose start and end time since this provides more useful information related to interviews. This also allows clashes to be identified and resolved. (e.g. interviews on the same day/overlapping time slot).

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: shashahchk/ped#6

**Comment by ghost** [comment]
Update the UG example to be correct.
