### ISSUE TITLE
[PE-D][Tester F] Find command not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T11-2/tp#200]
This is the entire list:

![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/a3db742e-966a-4eb6-bc2e-2afd61c68b19.png)

This is the output after command "filter-a n/a"

![image.png](https://raw.githubusercontent.com/shashahchk/ped/main/files/5458b421-37b0-476c-a150-9bc3015f5c06.png)

Expected output: successfully finds the entry with name "Abc" as the UG specifies that find is case-insensitive.

Actual output: no entries found

This command works when tested with "find-a n/james". 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: shashahchk/ped#10

**Comment by ghost** [comment]
Update the user guide to specify that that it only matches full matching words not all substrings
